config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :organizations

  resources :questionnaire_templates do
    resources :questionnaire_sections
  end

  resources :unit_types
  resources :input_types
  resources :option_types

  root 'welcome#index'

end

app/models/questionnaire_section.rb
class QuestionnaireSection < ActiveRecord::Base
	belongs_to	:questionnaire_template
	has_many	:questions
end

app/controllers/questionnaire_sections_controller.rb
class QuestionnaireSectionsController < ApplicationController
  before_filter :authenticate_user!
  before_action :load_questionnaire_template
  before_action :set_questionnaire_section, only: [:show, :edit, :update, :destroy]
  
  # GET /questionnaire_sections
  # GET /questionnaire_sections.json
  def index
    @questionnaire_sections = @qt.questionnaire_sections.all
  end

  # GET /questionnaire_sections/1
  # GET /questionnaire_sections/1.json
  def show  
    #I think we need to put something here
  end

  # GET /questionnaire_sections/new
  def new
    @questionnaire_section = @qt.questionnaire_sections.new
  end

  # GET /questionnaire_sections/1/edit
  def edit
  end

  # POST /questionnaire_sections
  # POST /questionnaire_sections.json
  def create
    @questionnaire_section = @qt.questionnaire_sections.new(questionnaire_section_params)

    respond_to do |format|
      if @questionnaire_section.save
        format.html { redirect_to [@qt, @questionnaire_section], notice: 'questionnaire section was successfully created.' }
        format.json { render :show, status: :created, location: @questionnaire_section }
      else
        format.html { render :new }
        format.json { render json: @questionnaire_section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questionnaire_sections/1
  # PATCH/PUT /questionnaire_sections/1.json
  def update
    respond_to do |format|
      if @questionnaire_section.update(questionnaire_section_params)
        format.html { redirect_to [@qt, @questionnaire_section], notice: 'questionnaire section was successfully updated.' }
        format.json { render :show, status: :ok, location: @questionnaire_section }
      else
        format.html { render :edit }
        format.json { render json: @questionnaire_section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questionnaire_sections/1
  # DELETE /questionnaire_sections/1.json
  def destroy
    @questionnaire_section.destroy
    respond_to do |format|
      format.html { redirect_to questionnaire_sections_url, notice: 'questionnaire section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def load_questionnaire_template
      @qt = QuestionnaireTemplate.find(params[:questionnaire_template_id])      
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_questionnaire_section
      @questionnaire_section = @qt.questionnaire_sections.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def questionnaire_section_params
      #params.require(:questionnaire_section).permit(:name, :title, :subtitle, :required_yn, questionnaire_template_attributes: [:id])
      params.require(:questionnaire_section).permit(:name, :title, :subtitle, :required_yn)
      #params[:questionnaire_section]
    end
end

app/helpers/questionnaire_sections_helper.rb
module QuestionnaireSectionsHelper
end

app/views/questionnaire_sections/_form.html.erb
<%= form_for([@qt, @questionnaire_section]) do |f| %>
  <% if @questionnaire_section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@questionnaire_section.errors.count, "error") %> prohibited this questionnaire_section from being saved:</h2>

      <ul>
      <% @questionnaire_section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :subtitle %><br>
    <%= f.text_field :subtitle %>
  </div>

  <div class="field">
    <%= f.select :required_yn, [["Yes", "Y"], ["No", "N"]] %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questionnaire_sections/edit.html.erb
<h1>Editing questionnaire Section</h1>

<%= render 'form' %>

<%= link_to 'Show', questionnaire_template_questionnaire_section_path(@qt, @questionnaire_section) %> |
<%= link_to 'Back', questionnaire_template_path(@qt) %>

app/views/questionnaire_sections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing questionnaire Sections</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questionnaire_sections.each do |questionnaire_section| %>
      <tr>
        <td><%= link_to 'Show', questionnaire_template_questionnaire_section(@qt, questionnaire_section) %></td>
        <td><%= link_to 'Edit', edit_questionnaire_template_questionnaire_section_path(@qt) %></td>
        <td><%= link_to 'Destroy', questionnaire_template_questionnaire_section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New questionnaire section', new_questionnaire_template_questionnaire_section_path %>

app/views/questionnaire_sections/new.html.erb
<h1>New questionnaire Section</h1>

<%= render 'form' %>

<%= link_to 'Back', questionnaire_template_questionnaire_sections_path %>

app/views/questionnaire_sections/show.html.erb
<p id="notice"><%= notice %></p>

<p><%= @questionnaire_section.name %></p>

<%= link_to 'Edit', edit_questionnaire_template_questionnaire_section_path %> |
<%= link_to 'Back', questionnaire_template_path(@qt) %>