config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :organizations

  resources :questionnaire_templates do
    resources :questionnaire_sections
  end

  resources :unit_types
  resources :input_types
  resources :option_types

  root 'welcome#index'

end

app/models/questionnaire_template.rb
class QuestionnaireTemplate < ActiveRecord::Base
	has_many :questionnaire_sections
	has_one	 :qt_type
end

app/controllers/questionnaire_templates_controller.rb
class QuestionnaireTemplatesController < ApplicationController\
  before_filter :authenticate_user!
  before_action :set_questionnaire_template, only: [:show, :edit, :update, :destroy]

  # GET /questionnaire_templates
  # GET /questionnaire_templates.json
  def index
    @questionnaire_templates = QuestionnaireTemplate.all

    flash.now[:notice] = "This is a test"

  end

  # GET /questionnaire_templates/1
  # GET /questionnaire_templates/1.json
  def show
  end

  # GET /questionnaire_templates/new
  def new
    @questionnaire_template = QuestionnaireTemplate.new
  end

  # GET /questionnaire_templates/1/edit
  def edit
  end

  # POST /questionnaire_templates
  # POST /questionnaire_templates.json
  def create
    @questionnaire_template = QuestionnaireTemplate.new(questionnaire_template_params)

    respond_to do |format|
      if @questionnaire_template.save
        format.html { redirect_to @questionnaire_template, notice: 'questionnaire template was successfully created.' }
        format.json { render :show, status: :created, location: @questionnaire_template }
      else
        format.html { render :new }
        format.json { render json: @questionnaire_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questionnaire_templates/1
  # PATCH/PUT /questionnaire_templates/1.json
  def update
    respond_to do |format|
      if @questionnaire_template.update(questionnaire_template_params)
        format.html { redirect_to @questionnaire_template, notice: 'questionnaire template was successfully updated.' }
        format.json { render :show, status: :ok, location: @questionnaire_template }
      else
        format.html { render :edit }
        format.json { render json: @questionnaire_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questionnaire_templates/1
  # DELETE /questionnaire_templates/1.json
  def destroy
    @questionnaire_template.destroy
    respond_to do |format|
      format.html { redirect_to questionnaire_templates_url, notice: 'questionnaire template was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_questionnaire_template
      @questionnaire_template = QuestionnaireTemplate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def questionnaire_template_params
      params.require(:questionnaire_template).permit(:name, :qt_type_id, :instructions, :comments)
    end
end

app/helpers/questionnaire_templates_helper.rb
module QuestionnaireTemplatesHelper
end

app/views/questionnaire_templates/_form.html.erb
<%= form_for(@questionnaire_template) do |f| %>
  <% if @questionnaire_template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@questionnaire_template.errors.count, "error") %> prohibited this questionnaire_template from being saved:</h2>

      <ul>
      <% @questionnaire_template.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :instructions %><br>
    <%= f.text_area :instructions %>
  </div>

  <div class="field">
    <%= f.collection_select :qt_type_id, QtType.all, :id, :descr %>
  </div>

  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_area :comments %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questionnaire_templates/edit.html.erb
<h1>Editing questionnaire Template</h1>

<%= render 'form' %>

<%= link_to 'Show', @questionnaire_template %> |
<%= link_to 'Back', questionnaire_templates_path %>

app/views/questionnaire_templates/index.html.erb
<h1>Listing questionnaire Templates</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questionnaire_templates.each do |questionnaire_template| %>
      <tr>
        <td><%= questionnaire_template.name %></td>
        <td><%= link_to 'Show', questionnaire_template %></td>
        <td><%= link_to 'Edit', edit_questionnaire_template_path(questionnaire_template) %></td>
        <td><%= link_to 'Destroy', questionnaire_template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New questionnaire template', new_questionnaire_template_path %>

app/views/questionnaire_templates/new.html.erb
<h1>New questionnaire Template</h1>

<%= render 'form' %>

<%= link_to 'Back', questionnaire_templates_path %>

app/views/questionnaire_templates/show.html.erb
<p id="notice"><%= notice %></p>

<table>
	<tr>
    	<th><%= @questionnaire_template.name %></th>
  	</tr>
 <% @questionnaire_template.questionnaire_sections.each do |section| -%>
	<tr>
		<td><%= section.name %></td>
		<td><%= link_to 'Edit', edit_questionnaire_template_questionnaire_section_path(@questionnaire_template, section) %></td>
	</tr>
	

<% end -%>
	<tr>
		<td></td>
	</tr>
	<tr>
		<td>
			<%= link_to 'Create New Section', new_questionnaire_template_questionnaire_section_path(@questionnaire_template) %>
		</td>
	</tr>
</table>
<br>
<br>
<%= link_to 'Edit', edit_questionnaire_template_path(@questionnaire_template) %> |
<%= link_to 'Back', questionnaire_templates_path %>