config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :organizations

  resources :questionnaire_templates do
    resources :questionnaire_sections
  end

  resources :unit_types
  resources :input_types
  resources :option_types

  root 'welcome#index'

end

app/controllers/input_types_controller.rb
class InputTypesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_input_type, only: [:show, :edit, :update, :destroy]

  # GET /input_types
  # GET /input_types.json
  def index
    @input_types = InputType.all
  end

  # GET /input_types/1
  # GET /input_types/1.json
  def show
  end

  # GET /input_types/new
  def new
    @input_type = InputType.new
  end

  # GET /input_types/1/edit
  def edit
  end

  # POST /input_types
  # POST /input_types.json
  def create
    @input_type = InputType.new(input_type_params)

    respond_to do |format|
      if @input_type.save
        format.html { redirect_to @input_type, notice: 'Input type was successfully created.' }
        format.json { render :show, status: :created, location: @input_type }
      else
        format.html { render :new }
        format.json { render json: @input_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /input_types/1
  # PATCH/PUT /input_types/1.json
  def update
    respond_to do |format|
      if @input_type.update(input_type_params)
        format.html { redirect_to @input_type, notice: 'Input type was successfully updated.' }
        format.json { render :show, status: :ok, location: @input_type }
      else
        format.html { render :edit }
        format.json { render json: @input_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /input_types/1
  # DELETE /input_types/1.json
  def destroy
    @input_type.destroy
    respond_to do |format|
      format.html { redirect_to input_types_url, notice: 'Input type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_input_type
      @input_type = InputType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def input_type_params
      params.require(:input_type).permit(:descr)
    end
end

app/helpers/input_types_helper.rb
module InputTypesHelper
end

app/views/input_types/_form.html.erb
<%= form_for(@input_type) do |f| %>
  <% if @input_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@input_type.errors.count, "error") %> prohibited this input_type from being saved:</h2>

      <ul>
      <% @input_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descr %><br>
    <%= f.text_field :descr %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/input_types/edit.html.erb
<h1>Editing Input Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @input_type %> |
<%= link_to 'Back', input_types_path %>

app/views/input_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Input Types</h1>

<table>
  <thead>
    <tr>
      <th>Descr</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @input_types.each do |input_type| %>
      <tr>
        <td><%= input_type.descr %></td>
        <td><%= link_to 'Show', input_type %></td>
        <td><%= link_to 'Edit', edit_input_type_path(input_type) %></td>
        <td><%= link_to 'Destroy', input_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Input type', new_input_type_path %>

app/views/input_types/new.html.erb
<h1>New Input Type</h1>

<%= render 'form' %>

<%= link_to 'Back', input_types_path %>

app/views/input_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descr:</strong>
  <%= @input_type.descr %>
</p>

<%= link_to 'Edit', edit_input_type_path(@input_type) %> |
<%= link_to 'Back', input_types_path %>